### ISSUE TITLE
npm start runs on   http://localhost:3000/frag rather than http://localhost:3000/

### ISSUE THREAD

**Issue by kamil200** [kamil200/frag#17]

**Comment by kamil200** [comment]
check it out!!

**Comment by adnanpatell** [comment]
noted

**Comment by adnanpatell** [comment]
The error is from the end point of github pages you might need to fix it
because your github pages extension shows /frag in the end which i removed
in package.json after that it didnt show any /frag kindly check github
pages and revert me back asap!

**Comment by kamil200** [comment]
you are fired!

**Comment by adnanpatell** [comment]
Fuck off Bro firing accepted
